#!/bin/bash

index_base="$1/index-START.html"
index="$1/index.html"
scripts_base="$1/scripts-START.js"
scripts="$1/scripts.js"
style_base="$1/style-START.css"
style="$1/style.css"

# Create project files from *-START.*
sed -e 's/  /\t/g' "$index_base" > "$index"
[ -f "$scripts_base" ] &&  sed -e 's/  /\t/g' "$scripts_base" > "$scripts"
[ -f "$style_base" ] && sed -e 's/  /\t/g' "$style_base" >"$style"

xdg-open "$index"
$EDITOR "$index"
while true; do
	read -p  "Finished exercise (add, commit, and push?)? " yn
	case $yn in
		[Yy]* ) 
			git add .
			git commit -m "Do exercise $(echo $1 | cut -f 1 -d " ")."
			git push
			break;;
		[Nn]* ) exit;; 
		* )
			echo "Please answer yes or no.";;
	esac
done
