#!/bin/bash
sed -e 's/  /\t/g' "$1/index-START.html" | iconv -c -f utf-8 -t ascii - > "$1/index.html"
xdg-open "$1/index.html"
$EDITOR "$1/index.html"
while true; do
	read -p  "Finished exercise (add, commit, and push?)? " yn
	case $yn in
		[Yy]* ) 
			git add "$1/index.html"
			git commit -m "Do exercise $(echo $1 | cut -f 1 -d " ")."
			git push
			break;;
		[Nn]* ) exit;; 
		* )
			echo "Please answer yes or no.";;
	esac
done
